name = "OverpassAPI"
uuid = "78759bb8-e702-4122-98f4-c2c710342d47"
version = "0.1.0"
authors = ["Josh Day <emailjoshday@gmail.com>"]

[deps]
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
GeoInterface = "1.6.0"
HTTP = "1.10.19"
JSON3 = "1.14.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
